language: node_js
node_js:
- node
before_script:
- npm install -g gulp-cli
- npm install
script: gulp production
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip_cleanup: true
  keep-history: true
  local-dir: dist
  target-branch: master
  on:
    branch: master

