language: node_js
node_js:
 - "node"
before_script:
  - npm install -g gulp-cli
  - npm install
script: gulp
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
on:
  tags: true